name: Arborist Run
on:
  workflow_dispatch:
    inputs:
      spec_branch:
        description: 'Branch with task-tree.json'
        required: true
        type: string
      tree_path:
        description: 'Path to task tree JSON'
        required: false
        default: 'task-tree.json'
        type: string
      runner_type:
        description: 'AI runner (claude, gemini, opencode)'
        required: false
        default: 'claude'
        type: string
      model:
        description: 'Model name'
        required: false
        default: 'sonnet'
        type: string
      max_retries:
        description: 'Max retries per task'
        required: false
        default: '5'
        type: string
      container_mode:
        description: 'Container mode (auto, enabled, disabled)'
        required: false
        default: 'auto'
        type: string

permissions:
  contents: write

jobs:
  run-arborist:
    runs-on: ubuntu-latest-m
    timeout-minutes: 720

    steps:
      # ── Setup ──────────────────────────────────────
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.spec_branch }}
          fetch-depth: 0

      - name: Pull existing arborist branches (resume support)
        run: |
          echo "Fetching arborist/* branches for resume support..."
          git fetch origin 'refs/heads/arborist/*:refs/remotes/origin/arborist/*' 2>/dev/null || true
          for rb in $(git branch -r --list 'origin/arborist/*' 2>/dev/null); do
            branch="${rb#origin/}"
            if ! git rev-parse --verify "$branch" >/dev/null 2>&1; then
              git branch "$branch" "$rb"
              echo "  Restored: $branch"
            fi
          done

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install agent-arborist
        run: pip install git+https://${{ secrets.GH_PAT_ARBORIST_RO }}@github.com/pennyworth-tech/agent-arborist.git

      - name: Install Claude Code
        if: inputs.runner_type == 'claude'
        run: npm install -g @anthropic-ai/claude-code

      - name: Install devcontainer CLI
        if: inputs.container_mode != 'disabled'
        run: npm install -g @devcontainers/cli

      - name: Configure environment
        run: |
          echo "CLAUDE_CODE_OAUTH_TOKEN=${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}" > .env
          mkdir -p .devcontainer
          cp .env .devcontainer/.env

      # ── Execute ────────────────────────────────────
      - name: Run gardener
        run: |
          arborist gardener \
            --tree "${{ inputs.tree_path }}" \
            --runner-type "${{ inputs.runner_type }}" \
            --model "${{ inputs.model }}" \
            --max-retries ${{ inputs.max_retries }} \
            --container-mode "${{ inputs.container_mode }}" \
            --base-branch "${{ inputs.spec_branch }}" \
            --log-dir .arborist/logs \
            --report-dir .arborist/reports
        env:
          CLAUDE_CODE_OAUTH_TOKEN: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

      # ── Teardown (always, even on failure) ─────────
      - name: Push arborist branches + base
        if: always()
        run: |
          echo "Pushing arborist branches to preserve progress..."
          for branch in $(git branch --list 'arborist/*' 2>/dev/null); do
            branch=$(echo "$branch" | xargs)
            git push origin "$branch" --force-with-lease 2>/dev/null || echo "  skip: $branch"
          done
          git push origin "${{ inputs.spec_branch }}" --force-with-lease 2>/dev/null || echo "  skip: base branch"

      - name: Generate status artifacts
        if: always()
        run: |
          mkdir -p .arborist/artifacts
          arborist status --tree "${{ inputs.tree_path }}" > .arborist/artifacts/status.txt 2>&1 || true
          cp "${{ inputs.tree_path }}" .arborist/artifacts/ 2>/dev/null || true

          # Per-task inspect reports
          python3 -c "
          import json
          tree = json.load(open('${{ inputs.tree_path }}'))
          for nid, node in tree.get('nodes', {}).items():
            if node.get('is_leaf', False): print(nid)
          " 2>/dev/null | while read tid; do
            arborist inspect --tree "${{ inputs.tree_path }}" --task-id "$tid" \
              > ".arborist/artifacts/inspect-${tid}.txt" 2>&1 || true
          done

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: arborist-run-${{ github.run_id }}
          path: |
            .arborist/artifacts/
            .arborist/logs/
            .arborist/reports/
          retention-days: 30
