"""Constants for agent-arborist."""

TRAILER_PREFIX = "Arborist"
TRAILER_STEP = f"{TRAILER_PREFIX}-Step"
TRAILER_RESULT = f"{TRAILER_PREFIX}-Result"
TRAILER_TEST = f"{TRAILER_PREFIX}-Test"
TRAILER_REVIEW = f"{TRAILER_PREFIX}-Review"
TRAILER_RETRY = f"{TRAILER_PREFIX}-Retry"
TRAILER_REPORT = f"{TRAILER_PREFIX}-Report"
TRAILER_REVIEW_LOG = f"{TRAILER_PREFIX}-Review-Log"
TRAILER_TEST_LOG = f"{TRAILER_PREFIX}-Test-Log"
TRAILER_TEST_TYPE = f"{TRAILER_PREFIX}-Test-Type"
TRAILER_TEST_PASSED = f"{TRAILER_PREFIX}-Test-Passed"
TRAILER_TEST_FAILED = f"{TRAILER_PREFIX}-Test-Failed"
TRAILER_TEST_SKIPPED = f"{TRAILER_PREFIX}-Test-Skipped"
TRAILER_TEST_RUNTIME = f"{TRAILER_PREFIX}-Test-Runtime"

# Legacy aliases
TRAILER_STATUS = TRAILER_RESULT
TRAILER_AGENT = f"{TRAILER_PREFIX}-Agent"
TRAILER_TEST_RESULT = TRAILER_TEST
TRAILER_PARENT_SHA = f"{TRAILER_PREFIX}-Parent-SHA"

DEFAULT_NAMESPACE = "arborist"
DEFAULT_MAX_RETRIES = 5
